### PR TITLE
Fix `FileDependenciesStrategy` when the dependency file is in a folder

### PR DESCRIPTION
**Pull request by alessiamarcolini**
## Before submitting checklist

- [x] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)
- [ ] Did you **ask the docs owner** to review all the user-facing changes?

### CODE REVIEW

**Comment by AleksanderWWW** [comment]
@alessiamarcolini please install and run pre-commit on your code :smile:

**Comment by alessiamarcolini** [comment]
@AleksanderWWW done :)

**Comment by AleksanderWWW** [comment]
@alessiamarcolini  Did you run the unittests on your branch :smile: ?

**Comment by alessiamarcolini** [comment]
@AleksanderWWW yes I did, passing :)

**Review by AleksanderWWW — DISMISSED** [review]

**Review by AleksanderWWW — APPROVED** [review]

**Pull request merged**
