### PR TITLE
fix: Fix tests with git repo

### PR DESCRIPTION
**Pull request by PatrykGala**
## Before submitting checklist

- [x] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)
- [x] Did you **ask the docs owner** to review all the user-facing changes?

### CODE REVIEW

**Comment by PatrykGala** [comment]
https://github.com/neptune-ai/neptune-client/actions/runs/5412153822

**Comment by PatrykGala** [comment]
https://github.com/neptune-ai/neptune-client/actions/runs/5412811799

**Comment by jdudycz** [comment]
`test_get_uncommitted_changes_clean_repo` unit test is failing

**Review by jdudycz — APPROVED** [review]

**Pull request merged**
