### PR TITLE
change: get all values from a given path, if possible

### PR DESCRIPTION
**Pull request by janbolle**
Dear Neptune-Team,

I didn't found the possibility to get back a path (like 'params') as a `dict` from a certain run.
This might be helpful if you initialize a model using the params as a `dict` and you don't know each param of each model to construct.
So I added two functions.

I would really be happy if you either could accept my pull request or tell me how I can achieve this in another way.
(unfortunately, I was not able to get your unit tests running, so I skipped writing a test 😕 

Thank you very much.

### CODE REVIEW

**Comment by aniezurawski** [comment]
Hi @janbolle 

We have this feature in out backlog. Actually it is planned to be done next week.
You can find out spec here:
https://docs.google.com/document/d/1Zotebz5a5uDrSwPukTzi3XLV-s2_xrXPZ8T-fchUZ_Y/edit?usp=sharing

Let me know if this is what you want to achieve. :)

**Comment by janbolle** [comment]
Nice!
Exactly what I am thinking about!

**Comment by janbolle** [comment]
Any news on that, @aniezurawski?

**Comment by aniezurawski** [comment]
Actually yes. You can observe this pull request: https://github.com/neptune-ai/neptune-client/pull/549
I hope it will be released next week.

**Comment by aniezurawski** [comment]
Hi @janbolle 

This pull request was merged and released yesterday.

**Pull request closed without merging**
