### PR TITLE
remove `AbstractNeptuneObject`

### PR DESCRIPTION
**Pull request by szysad**
## Before submitting checklist

- [x] Did you **update the CHANGELOG**? (not for test updates, internal changes/refactors or CI/CD setup)
- [x] Did you **ask the docs owner** to review all the user-facing changes?

### CODE REVIEW

**Review by AleksanderWWW — COMMENTED** [review]
For `get_root_object` method in `handler.Handler` PyCharm now complains that the return type hint is inaccurate:
`Expected type 'NeptuneObject', got 'MetadataContainer' instead`

**Review by normandy7 — COMMENTED** [review]
I assume this doesn't affect usage of `NeptuneObject` or `NeptuneObjectCallback` for the end user?

**Comment by szysad** [comment]
> I assume this doesn't affect usage of `NeptuneObject` or `NeptuneObjectCallback` for the end user?

@normandy7 It only changes typehint in `stop_synchronization_callback()` which is part of api

**Comment by szysad** [comment]
> get_root_object

@AleksanderWWW can you double check and restart pycharm? On this branch `MetadataContainer` doesn't even exist.
Or can you past the error message?

**Comment by AleksanderWWW** [comment]
@szysad you're right, my pyCharm instance had a lag or something. All is well.

**Review by AleksanderWWW — APPROVED** [review]

**Review by AleksanderWWW — APPROVED** [review]

**Pull request merged**
